name: Claude Assistant

on:
  issue_comment:
    types: [created, edited]

jobs:
  post_claude_response:
    if: contains(github.event.comment.body, 'claude')
    runs-on: ubuntu-latest

    steps:
    - name: Get stripped comment body
      id: get-comment-body
      run: echo comment=$(echo ${{github.event.comment.body}}) >> $GITHUB_OUTPUT

    - name: Get Claude's response to issue comment
      id: claude-response
      if: steps.get-comment-body.outputs.comment != ''
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        echo response=$(curl https://api.anthropic.com/v1/messages \
            --header "x-api-key: $ANTHROPIC_API_KEY" \
            --header "anthropic-version: 2023-06-01" \
            --header "content-type: application/json" \
            --data \
            '{
                "model": "claude-3-opus-20240229",
                "max_tokens": 1024,
                "messages": [
                    {"role": "user", "content": "${{ steps.get-comment-body.outputs.comment }}"}
                ]
            }') >> $GITHUB_OUTPUT

    - name: Create comment
      if: steps.get-comment-body.outputs.comment != '' && steps.claude-response.outcome == 'success'
      uses: peter-evans/create-or-update-comment@v4
      with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            @!claude_response

            > ${{ steps.get-comment-body.outputs.comment }}

            ${{ fromJson(steps.claude-response.outputs.response).content[0].text }}
